### ISSUE TITLE
License file not found for notify:5.1.0

### ISSUE THREAD

**Issue by dergecko** [sstadick/cargo-bundle-licenses#13]
For the crate [notify](https://crates.io/crates/notify) the license is not correctly added to the bundled file.

Instead of copying the license file `bundle-licenses` just posts the string path into the licenses text field:
```yaml
  - package_name: notify
    package_version: 5.1.0
    license: CC0-1.0 OR Artistic-2.0
    licenses:
      - license: CC0-1.0
        text: "../LICENSE"
      - license: Artistic-2.0
        text: "../LICENSE"
```

If you need further information feel free to reach out to me.
