### ISSUE TITLE
LICENSE-BSD text not found for `zerocopy`

### ISSUE THREAD

**Issue by balins** [sstadick/cargo-bundle-licenses#44]
Hi,
I've ran the command to generate `THIRDPARTY.yml` and it did great for the vast majority of the crates, but not for [zerocopy](https://crates.io/crates/zerocopy) and [zerocopy-derive](https://crates.io/crates/zerocopy-derive). The first one has `LICENSE-BSD` at it's root and the other one has a symlink named `LICENSE-BSD` pointing to that root license. `cargo-bundle-licenses` correctly detected BSD-2-Clause licenses, but was unable to find their texts:
```
  licenses:
  - license: BSD-2-Clause
    text: NOT FOUND
  - license: Apache-2.0
    ...
```
Both crates are quite popular judging by the number of downloads, so it would be great to fix this. Unfortunately, I'm not even sure where to start.
